name: dart_express
description: An unopinionated express-like HTTP framework built in Dart, includes the ability to render Mustache, Jael and HTML files, and simple routing.
version: 0.5.3
homepage: https://github.com/deriegle/dart-express

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  path: ^1.6.4
  file: ^6.0.0
  http: ^1.0.0
  meta: ^1.7.0
  path_to_regexp: ^0.2.1
  mustache4dart: ^3.0.0-dev.0.0
  markdown: ^4.0.1

dev_dependencies:
  mockito: ^5.0.17
  test: ^1.20.1
  lints: ^1.0.1
