name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v3
      - run: pub get
      - run: dart test
      - run: dart analyze 
